name: CI/CD Pipeline for Parcel Tracker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Lints and Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install SQLite3
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Create and initialize database
      run: |
        sqlite3 tracker.db "
        CREATE TABLE parcel (
            number INTEGER PRIMARY KEY AUTOINCREMENT,
            client INTEGER NOT NULL,
            status TEXT NOT NULL,
            address TEXT NOT NULL,
            created_at TEXT NOT NULL
        );
        "
        sqlite3 tracker.db ".tables"

    - name: Run Go Vet
      run: go vet ./...

    - name: Run Tests
      run: go test -v -timeout 30s ./...

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: success() && startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Debug info
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
        echo "Test result: ${{ needs.test.result }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: postkserks/parcel-tracker
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}