name: CI/CD Pipeline for Parcel Tracker

on:
  push:
    branches: [main]
    tags: ['v*.*.*'] 
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install SQLite3
        run: sudo apt-get update && sudo apt-get install -y sqlite3

      - name: Create and initialize database
        run: |
          sqlite3 tracker.db "
          CREATE TABLE parcel (
              number INTEGER PRIMARY KEY AUTOINCREMENT,
              client INTEGER NOT NULL,
              status TEXT NOT NULL,
              address TEXT NOT NULL,
              created_at TEXT NOT NULL
          );
          "
          sqlite3 tracker.db ".tables"

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Tests
        run: go test -v -timeout 30s ./...

  docker-publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: test

    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub

        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image

        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            postkserks/parcel-tracker:${{ github.ref_name }}  
            postkserks/parcel-tracker:latest

      - name: Simulate Docker build for PR

        if: github.event_name == 'pull_request'
        run: |
          echo "Simulating Docker build for PR..."
          echo "Image would be: postkserks/parcel-tracker:test"